// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktszqfboglhilbzmeasb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0c3pxZmJvZ2xoaWxiem1lYXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTgzNzMsImV4cCI6MjA3MTI3NDM3M30.L_fmiVvTS5Mphk3dSiHOzdQxZBbwwd-t28fAURjm31c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});